# Build instructions:
#   - runs linter
#   - DOES NOT run dependency vulnerability scan BUT IT SHOULD
#   - runs build
#   - Pushes package to private npm repo


version: 0.2

env:
  parameter-store:
    NPM_TOKEN: /secrets/ops/us-east-1/build-pipelines/shared/npm_token

phases:
  install:
    commands:
      # install dependencies
      - npm install
      - npm version -no-git-tag-version $CODEBUILD_SOURCE_VERSION


  build:
    commands:
      - npm publish

